[package]
name = "mt"
author = "Santo Cariotti <santo@dcariotti.me>"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = { version = "0.4.3", optional = true }
sha2 = { version = "0.10.9", optional = true }

[features]
default = []
sha256 = ["sha2", "hex"]
